Repository Yuqzii/Konkurransetilsynet, pull requests merged in 2025-05, with the labels that each got.

#1 feat: separate messages into command and arguments
  main.go
Labels: enhancement

#14 feat(ci): separate environments for prod and dev
  .github/workflows/deploy.yml
  cmd/main.go
  internal/guessTheFunction/ast.go
  internal/guessTheFunction/function.go
  internal/guessTheFunction/parser.go
  internal/messageCommands.go
Labels: type: enhancement

#19 feat(ci): change to periodically pulling repo on server
  .github/workflows/deploy_prod.yml
  .gitignore
  docker-compose.yml
  update-server.sh
Labels: type: ci/cd

#21 fix(ci): change name of dev container image
  docker-compose_dev.yml
Labels: type: ci/cd

#24 feat(commands): basic upcoming Codeforces contests list
  cmd/main.go
  internal/codeforces/codeforces.go
  internal/codeforces/listContests.go
Labels: type: enhancement

#25 feat: show relative time until contests
  internal/codeforces/listContests.go
Labels: type: enhancement

#26 feat: sort contests by start time
  internal/codeforces/listContests.go
Labels: type: enhancement

#27 feat(codeforces): list upcoming contests
  .github/workflows/deploy_prod.yml
  cmd/main.go
  internal/codeforces/codeforces.go
  internal/codeforces/listContests.go
Labels: type: enhancement

#33 feat(cf): contest ping (testing)
  cmd/main.go
  internal/codeforces/codeforces.go
  internal/codeforces/contestPing.go
  internal/codeforces/listContests.go
Labels: type: enhancement

#37 bugfix(cf): pinging contest multiple times
  internal/codeforces/codeforces.go
  internal/codeforces/contestPing.go
Labels: type: bug

#38 fix(cf): try initing ping channel after session opens
  cmd/main.go
  internal/codeforces/codeforces.go
  internal/codeforces/contestPing.go
Labels: type: bug

#39 refactor(cf): change structure to functional
  cmd/main.go
  internal/codeforces/codeforces.go
  internal/codeforces/contestPing.go
  internal/codeforces/listContests.go
Labels: type: refactor

#41 feat(ci): fail check if formatting is wrong
  .github/workflows/build.yml
Labels: type: ci/cd

#43 feat(cf): find or create ping role
  internal/codeforces/codeforces.go
  internal/codeforces/contestPing.go
Labels: type: enhancement

#47 feat(ci): restart container on crash
  docker-compose.yml
  docker-compose_dev.yml
Labels: type: ci/cd

#49 feat(cf): improve display of contest list
  internal/codeforces/listContests.go
Labels: type: enhancement

#45 refactor: ast, expr and parser
  internal/guessTheFunction/ast.go
  internal/guessTheFunction/expr.go
  internal/guessTheFunction/expr_json.go
  internal/guessTheFunction/function.go
  internal/guessTheFunction/guessTheFunction_test.go
  internal/guessTheFunction/guessTheFunction_testcases.go
  internal/guessTheFunction/parser.go
Labels: type: refactor

#56 feat: create postgres database
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
  cmd/main.go
  dbinit/user_data.sql
  docker-compose.yml
  docker-compose_dev.yml
  go.mod
  go.sum
  internal/database/database.go
Labels: type: enhancement
